name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  run:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        # arch: ["armv6", "armv7", "aarch64", "amd64"]
        php: ["8.0", "8.1", "8.2", "8.3", "8.4"]
        type: ["ts", "nts"]
    steps:
    - name: Checkout code
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libi2c-dev -y

    - name: Setup PHP
      uses: shivammathur/setup-php@bf6b4fbd49ca58e4608c9c89fba0b8d90bd2a39f # v2.35.5
      with:
        php-version: ${{ matrix.php }}
        coverage: none
        extensions: none
        tools: none
      env:
        phpts: ${{ matrix.type }}
        update: true

    - name: Prepare for build
      run: phpize && ./configure

    - name: Build ext-i2c
      run: make

    - name: Run test suite
      run: make test
      env:
        NO_INTERACTION: 1
